spring:
  data:
    redis:
      host: localhost
      port: 6380
  kafka:
    bootstrap-servers: 34.42.237.145:9093
    consumer:
      auto-offset-reset: latest
      group-id: notify
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  datasource:
    url: jdbc:mysql://34.42.237.145:3306/notify?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: BAND-NOTIFY-SERVICE

server:
  port: 8000

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,beans,refresh

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
#

